[workspace]
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
name = "expression_lib"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.88.0,<1.89"
rust-src = ">=1.88.0,<2"
compilers = ">=1.11.0,<2"
clang = ">=20.1.8,<21"
